#!/usr/bin/env -S vp exec tsx
//MISE description="Generate per-workspace ports and .env.development.local"
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { realpathSync, writeFileSync } from 'node:fs'
import { basename } from 'node:path'

// ===== shared =====

function run(command: string, args: string[], timeout?: number): string {
	return execFileSync(command, args, {
		encoding: 'utf8',
		stdio: ['ignore', 'pipe', 'ignore'],
		timeout,
	}).trim()
}

// ===== config =====

const POSTGRES_USER = 'app_user'

const POSTGRES_PASSWORD = 'app_dev'

const AWS_ACCESS_KEY_ID = 'app_minio'

const AWS_SECRET_ACCESS_KEY = 'app_minio_secret'

// Varlock reads this header to treat generated values as non-sensitive.
const VARLOCK_HEADER = ['# ---', '# @defaultSensitive=false', '# ---', '']

// ===== derivations =====

function hash64(value: string): bigint {
	return BigInt(
		'0x' + createHash('sha256').update(value).digest('hex').slice(0, 16),
	)
}

// One contiguous block per workspace: four independent draws collide across
// the machine's workspaces roughly twice as often, surfacing as a compose
// bind failure at bootstrap. The block stays below the ephemeral port range.
function portBase(value: string): number {
	return 10_000 + Number(hash64(value) % 22_760n)
}

// 10/8 keeps explicit subnets clear of Docker's default pools (172.16/12,
// 192.168/16), whose space is what runs out on workspace-heavy machines.
function dockerSubnet(appPort: number): string {
	const block = appPort - 10_000

	return `10.${block >> 8}.${block & 0xff}.0/24`
}

function sanitizeDatabaseName(value: string): string {
	let result = value
		.replace(/[A-Z]/g, (character) => character.toLowerCase())
		.replace(/[^a-z0-9]+/g, '_')
		.replace(/^_+/, '')

	if (!result) result = 'workspace'

	if (!/^[a-z]/.test(result)) result = `w_${result}`
	result = result.slice(0, 44)

	if (!result.endsWith('_')) result += '_'

	return `${result}${hash64(value).toString(36).padStart(3, '0').slice(0, 3)}`
}

function slugify(value: string): string {
	const slug = value
		.toLowerCase()
		.replaceAll(/[^a-z0-9-]+/g, '-')
		.replaceAll(/-+/g, '-')
		.replace(/^-+|-+$/g, '')

	if (!slug) return 'workspace'

	if (slug.length <= 63) return slug

	const suffix = hash64(value).toString(36).padStart(8, '0').slice(0, 8)

	return `${slug.slice(0, 63 - suffix.length - 1).replace(/-+$/, '')}-${suffix}`
}

// ===== workspace =====

interface WorkspaceInfo {
	branch: string
	worktree: string
	// stable across branch switches: the jj workspace name, or the worktree
	// directory name on plain Git
	id: string
}

function detectWorkspace(): WorkspaceInfo {
	try {
		const root = realpathSync(run('jj', ['workspace', 'root']))

		const rows = run('jj', [
			'workspace',
			'list',
			'-T',
			'name ++ "\\t" ++ try(root.absolute(), "") ++ "\\n"',
		])

		for (const row of rows.split('\n')) {
			const [name, path] = row.split('\t')

			try {
				if (name && path && realpathSync(path) === root) {
					return { branch: name, worktree: basename(root), id: name }
				}
			} catch {
				// stale workspace whose directory is gone
			}
		}
	} catch {
		// not a jj repo
	}

	try {
		const root = realpathSync(run('git', ['rev-parse', '--show-toplevel']))

		return {
			branch: run('git', ['branch', '--show-current']) || basename(root),
			worktree: basename(root),
			id: basename(root),
		}
	} catch {
		throw new Error('Run setup from inside a jj workspace or Git worktree')
	}
}

function defaultWorkspaceRoot(): string {
	try {
		return realpathSync(run('jj', ['workspace', 'root', '--name', 'default']))
	} catch {
		// not a jj repo — the current directory is the root
		return realpathSync('.')
	}
}

// ===== env file =====

// A pure cache of workspace identity: never read back, deleted freely,
// regenerated identically. wt's copy-ignored cloning of another workspace's
// file is therefore harmless, and local hand edits do not survive a run.
function writeEnvFile(path: string, groups: Record<string, string>[]): void {
	const lines = [
		...VARLOCK_HEADER,
		'# Generated by mise run setup — do not edit.',
	]

	groups.forEach((group, index) => {
		if (index > 0) lines.push('')

		for (const [key, value] of Object.entries(group))
			lines.push(`${key}="${value}"`)
	})

	writeFileSync(path, `${lines.join('\n')}\n`)
}

// ===== pitchfork =====

// A stuck daemon socket would hang the run, so pitchfork calls get a timeout.
function pitchfork(args: string[]): string {
	return run('pitchfork', args, 10_000)
}

interface ProxyStatus {
	tld: string
	slugs: { slug: string; dir: string }[]
}

function proxyStatus(): ProxyStatus | null {
	try {
		const status: ProxyStatus = JSON.parse(
			pitchfork(['proxy', 'status', '--json']),
		)

		return status
	} catch {
		return null
	}
}

// A custom TLD with a public suffix (e.g. lvh.example.com) keeps slug URLs
// registrable as OAuth redirect URIs; the default 'localhost' is not.
// Two-level subdomains (`<ws>.<project>`) are not registered proxy routes:
// they silently serve the default app, so each workspace claims one
// single-label slug namespaced by project: `imdbgraph` for the default
// workspace, `imdbgraph-<workspace>` otherwise. Bare worktree names are
// taken (slug and pitchfork namespace are global registries), so the
// project prefix also keeps different projects' same-named worktrees from
// colliding. `proxy add` overwrites without asking, so a slug is claimed
// only when no other directory owns it. Null when pitchfork is unavailable
// or the slug is owned elsewhere. `proxy trust` needs sudo, so it stays a
// one-time manual step.
function proxySlugName(mainRoot: string, worktree: string): string {
	const projectSlug = slugify(basename(mainRoot))

	return realpathSync('.') === mainRoot
		? projectSlug
		: slugify(`${projectSlug}-${worktree}`)
}

function registerProxyUrl(namespace: string): string | null {
	const status = proxyStatus()

	if (!status) return null

	const cwd = realpathSync('.')

	try {
		pitchfork(['settings', 'set', 'proxy.enable', 'true', '--global'])

		const owner = status.slugs.find(({ slug }) => slug === namespace)?.dir

		let claimable = true

		if (owner !== undefined) {
			try {
				claimable = realpathSync(owner) === cwd
			} catch {
				// stale registration, the directory is gone
			}
		}

		if (!claimable) return null

		pitchfork(['proxy', 'add', namespace, '--daemon', 'dev', '--dir', cwd])

		return `https://${namespace}.${status.tld ?? 'localhost'}`
	} catch {
		return null
	}
}

// The daemon definition lives here, not in the tracked pitchfork.toml: any
// daemon-bearing file without an explicit namespace is also read under the
// directory basename, which would register a phantom daemon per workspace.
// The proxy must not guess which listening socket is the app (vite+/nitro
// opens several), so the port is pinned too. The namespace is pinned because
// pitchfork's default is the directory basename, a global registry that
// collides across projects.
function writeDaemonConfig(appPort: number, namespace: string): void {
	writeFileSync(
		'pitchfork.local.toml',
		`#:schema https://pitchfork.jdx.dev/schema.json

# Generated by mise run setup — do not edit.
namespace = "${namespace}"

[daemons.dev]
run = "exec vp dev"
mise = true
auto = ["start", "stop"]
retry = 3
ready_output = "Local:"
port = ${appPort}
`,
	)
}

// ===== main =====

function main(): void {
	const { branch, worktree, id } = detectWorkspace()
	const mainRoot = defaultWorkspaceRoot()

	// the workspace name is only unique within a repo, so the project's
	// main-root basename joins the hash to keep port blocks project-local
	const appPort = portBase(`${basename(mainRoot)}-${id}`)
	const postgresPort = appPort + 1
	const minioPort = appPort + 2
	const minioConsolePort = appPort + 3
	const database = sanitizeDatabaseName(id)

	const namespace = proxySlugName(mainRoot, worktree)
	const proxyUrl = registerProxyUrl(namespace)

	writeEnvFile('.env.development.local', [
		{
			APP_PORT: String(appPort),
			BASE_URL: proxyUrl ?? `http://localhost:${appPort}`,
		},
		{
			POSTGRES_PORT: String(postgresPort),
			POSTGRES_DB: database,
			POSTGRES_USER,
			POSTGRES_PASSWORD,
			DATABASE_URL:
				'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}',
		},
		{
			MINIO_PORT: String(minioPort),
			MINIO_CONSOLE_PORT: String(minioConsolePort),
		},
		{
			AWS_ENDPOINT_URL: 'http://localhost:${MINIO_PORT}',
			AWS_ACCESS_KEY_ID,
			AWS_SECRET_ACCESS_KEY,
			AWS_S3_BUCKET_NAME: 'app',
		},
		{
			WORKTREE_NAME: worktree,
			COMPOSE_PROJECT_NAME: sanitizeDatabaseName(worktree),
			DOCKER_SUBNET: dockerSubnet(appPort),
		},
	])

	writeDaemonConfig(appPort, namespace)

	console.log(`Generated .env.development.local for ${branch}:`)
	console.log(`  app:      http://localhost:${appPort}`)
	console.log(`  postgres: localhost:${postgresPort}/${database}`)
	console.log(`  minio:    http://localhost:${minioPort}`)

	if (proxyUrl) console.log(`  proxy:    ${proxyUrl}`)
}

main()
